// ─────────────────────────────────────────────────────────────
// Express entry point — already complete.
// Prisma is connected on startup; the threads router is mounted at /api/threads.
// You do NOT edit this file. Your work is in routes/threads.js.
// ─────────────────────────────────────────────────────────────
import "dotenv/config";
import express from "express";
import cors from "cors";
import threadsRouter from "./routes/threads.js";
import prisma from "./prisma/client.js";

const app = express();
app.use(cors());
app.use(express.json());

app.use("/api/threads", threadsRouter);

const PORT = 3001;

async function start() {
  await prisma.$connect();
  console.log("✅ Prisma connected to the database");
  app.listen(PORT, () => {
    console.log(`✅ Threadbase API running on http://localhost:${PORT}`);
  });
}

start().catch((err) => {
  console.error("❌ Failed to start — check DATABASE_URL and that PostgreSQL is running.");
  console.error(err);
  process.exit(1);
});
